apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 879273453659.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newName: 879273453659.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newTag: af348191
resources:
- ../../base
patchesStrategicMerge:
- front-deployment-patch.yaml
- front-service-patch.yaml
